global:
    api-listen-addr: :5183
    timeout: 10s
    memo: SW33 | pro-nodes Rly v2.
    light-cache-size: 20
chains:
    gaia:
        type: cosmos
        value:
            key: cosmos_wallet
            chain-id: GAIA
            rpc-addr: http://78.107.234.44:36657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001uatom
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    stride:
        type: cosmos
        value:
            key: stride_wallet
            chain-id: STRIDE-TESTNET-4
            rpc-addr: http://127.0.0.1:26757
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001ustrd
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
paths:
    stride-gaia:
        src:
            chain-id: STRIDE-TESTNET-4
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-0
                - channel-1
                - channel-2
                - channel-3
                - channel-4
