default_chain: stride
chains:
  gaia:
    key: cosmos_wallet
    chain-id: GAIA
    rpc-addr: http://78.107.234.44:36657
    grpc-addr: http://78.107.234.44:9797
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /home/rlyuser/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride:
    key: stride_wallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26757
    grpc-addr: http://127.0.0.1:9070
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /home/rlyuser/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
